worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream vm_backend {
        # Example VMs inside bridge network
        server 10.10.0.10:80;
        server 10.10.0.11:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://vm_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }
    }
}
